# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NationalParks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NationalParks
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'NationalParksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NationalParksUITests' do
    # Pods for testing
  end

end
